# Source artwork is organized here; installed paths stay compatible with saves
# and the runtime. Source pixels are copied verbatim.
function(fr_asset source runtime)
  set(input "${CMAKE_SOURCE_DIR}/assets/${source}")
  configure_file("${input}" "${CMAKE_BINARY_DIR}/${runtime}" COPYONLY)
  get_filename_component(folder "${runtime}" DIRECTORY)
  get_filename_component(name "${runtime}" NAME)
  if(NOT folder)
    set(folder ".")
  endif()
  install(FILES "${input}" DESTINATION "${FR_ASSET_INSTALL_PREFIX}${folder}" RENAME "${name}")
endfunction()
foreach(effect Follower_ComeInOut Follower_Emote1 Follower_Emote2 Follower_Emote3)
  fr_asset("follower-effects/${effect}.png" "LocalAssets/Follower effects/${effect}.png")
endforeach()
include(cmake/FollowerAssets.cmake)
foreach(name IN LISTS FR_FOLLOWER_NAMES)
  fr_asset("followers/${name}.png" "LocalAssets/Followers/${name}.png")
  fr_asset("followers-shiny/${name}.png" "LocalAssets/Followers shiny/${name}.png")
endforeach()
install(FILES assets/credits/Following-Pokemon-EX.txt DESTINATION "${FR_ASSET_INSTALL_PREFIX}licenses" RENAME Following-Pokemon-EX-credits.txt)
fr_asset("cartridge/Fire Red Cart Art.png" "Cart Art/Fire Red Cart Art.png")
fr_asset("cartridge/Leaf Green Cart Art.png" "Cart Art/Leaf Green Cart Art.png")
fr_asset("controller/ob0008_00_gadgets.dae" "Poké Ball Plus/ob0008_00_gadgets.dae")
fr_asset("controller/ob0008_00_obj_col.png" "Poké Ball Plus/ob0008_00_obj_col.png")
foreach(font PixelOperator.ttf PixelOperator-Bold.ttf PixelOperatorMono.ttf PixelOperator8.ttf)
  fr_asset("fonts/${font}" "Fonts/${font}")
endforeach()
foreach(tile "Upper Left Corner" "Upper Middle Tile" "Upper Right Corner" "Left Middle Tile" "Middle Tile" "Right Middle Tile" "Bottom Left Corner" "Bottom Middle Tile" "Bottom Right Corner" "Thin Left Tile" "Thin Middle Tile" "Thin Right Tile")
  fr_asset("chat/${tile}.png" "Fonts/CHAT BUBBLE TILES/${tile}.png")
endforeach()
fr_asset("ui/Program_Icon.png" "Program_Icon.png")
fr_asset("ui/Party Icon.png" "UI Artwork/Party Icon.png")
fr_asset("ui/Party Icon_Egg.png" "UI Artwork/Party Icon_Egg.png")
foreach(frame 1 2 3)
  fr_asset("camp/Tent_f${frame}.png" "Camp/Tent_f${frame}.png")
endforeach()
