set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)
set(CMAKE_OSX_DEPLOYMENT_TARGET "12.0" CACHE STRING "Minimum macOS version")
enable_language(OBJC OBJCXX)
add_compile_definitions(SDL_MAIN_HANDLED)
include(cmake/Dependencies.cmake)
execute_process(COMMAND xcrun --sdk macosx --show-sdk-path OUTPUT_VARIABLE FR_MAC_SDK OUTPUT_STRIP_TRAILING_WHITESPACE COMMAND_ERROR_IS_FATAL ANY)
add_library(fr_core src/platform/image_mac.cpp src/platform/text_mac.cpp src/platform/log.cpp src/rom/zip.cpp src/rom/rom.cpp src/frontend/profile.cpp src/frontend/world_store.cpp src/runtime/probe.cpp)
target_include_directories(fr_core PUBLIC src "${CMAKE_BINARY_DIR}/generated")
target_link_libraries(fr_core PUBLIC zlibstatic "-framework Security" "-framework CoreFoundation" "-framework ImageIO" "-framework CoreGraphics")
add_library(fr_online src/online/connection.cpp src/online/campaign.cpp src/game/released.cpp src/game/camp.cpp src/online/session.cpp src/online/world_sync.cpp src/online/wager.cpp)
target_link_libraries(fr_online PUBLIC fr_core "-lcurl")
add_library(fr_imgui STATIC third_party/imgui/imgui.cpp third_party/imgui/imgui_draw.cpp third_party/imgui/imgui_widgets.cpp third_party/imgui/imgui_tables.cpp third_party/imgui/backends/imgui_impl_sdl2.cpp third_party/imgui/backends/imgui_impl_sdlrenderer2.cpp)
target_include_directories(fr_imgui PUBLIC third_party/imgui)
target_link_libraries(fr_imgui PUBLIC SDL2-static)
add_library(fr_labels src/game/labels.cpp src/game/follower_art.cpp)
target_link_libraries(fr_labels PUBLIC fr_core fr_imgui)
add_library(fr_ball_model src/frontend/ball_model.cpp)
target_include_directories(fr_ball_model PRIVATE "${FR_MAC_SDK}/usr/include/libxml2")
target_link_libraries(fr_ball_model PUBLIC fr_core PRIVATE "-lxml2")
add_library(fr_pokeball src/input/pokeball_mac.cpp src/input/pokeball_controls.cpp)
target_link_libraries(fr_pokeball PUBLIC fr_core)
add_executable(pokemulti src/frontend/launcher_mac.mm src/frontend/cartridge.cpp)
target_link_libraries(pokemulti PRIVATE fr_core fr_online fr_imgui "-framework AppKit")
add_executable(pokemulti_game src/runtime/game_main.cpp src/game/world.cpp src/online/panel.cpp)
target_link_libraries(pokemulti_game PRIVATE fr_core fr_online fr_imgui fr_labels fr_ball_model fr_pokeball gbarecomp_runtime)
set(MAC_APP "PokeMulti.app/Contents")
install(TARGETS pokemulti pokemulti_game RUNTIME DESTINATION "${MAC_APP}/MacOS")
configure_file(installer/Info.plist.in Info.plist @ONLY)
install(FILES "${CMAKE_BINARY_DIR}/Info.plist" DESTINATION "${MAC_APP}")
include(cmake/FollowerAssets.cmake)
foreach(name IN LISTS FR_FOLLOWER_NAMES)
  configure_file("LocalAssets/Followers/${name}.png" "LocalAssets/Followers/${name}.png" COPYONLY)
  install(FILES "LocalAssets/Followers/${name}.png" DESTINATION "${MAC_APP}/MacOS/LocalAssets/Followers")
endforeach()
foreach(folder "Fonts" "Camp" "Cart Art" "UI Artwork")
  file(GLOB_RECURSE assets RELATIVE "${CMAKE_SOURCE_DIR}" "${folder}/*.png" "${folder}/*.ttf")
  foreach(asset IN LISTS assets)
    configure_file("${asset}" "${asset}" COPYONLY)
    get_filename_component(subdir "${asset}" DIRECTORY)
    install(FILES "${asset}" DESTINATION "${MAC_APP}/MacOS/${subdir}")
  endforeach()
endforeach()
foreach(asset "Program_Icon.png" "Poké Ball Plus/ob0008_00_gadgets.dae" "Poké Ball Plus/ob0008_00_obj_col.png")
  configure_file("${asset}" "${asset}" COPYONLY)
  get_filename_component(subdir "${asset}" DIRECTORY)
  install(FILES "${asset}" DESTINATION "${MAC_APP}/MacOS/${subdir}")
endforeach()
install(FILES README.md docs/THIRD_PARTY.md LocalAssets/Following-Pokemon-EX-credits.txt dependencies.json DESTINATION "${MAC_APP}/Resources")
install(FILES third_party/gbarecomp/LICENSE third_party/gbarecomp/MPL-2.0.txt third_party/gbarecomp/UPSTREAM-JRICKEY-MIT.txt third_party/gbarecomp/THIRD_PARTY_ATTRIBUTION.md DESTINATION "${MAC_APP}/Resources/licenses")
install(FILES third_party/gbarecomp/external/arm-recomp-core/LICENSE DESTINATION "${MAC_APP}/Resources/licenses" RENAME arm-recomp-core-MIT.txt)
install(FILES third_party/SDL2/LICENSE.txt DESTINATION "${MAC_APP}/Resources/licenses" RENAME SDL2-zlib.txt)
install(FILES third_party/zlib/LICENSE DESTINATION "${MAC_APP}/Resources/licenses" RENAME zlib.txt)
install(FILES third_party/imgui/LICENSE.txt DESTINATION "${MAC_APP}/Resources/licenses" RENAME ImGui-MIT.txt)
install(FILES third_party/gbarecomp/third_party/tomlpp/LICENSE DESTINATION "${MAC_APP}/Resources/licenses" RENAME tomlplusplus-MIT.txt)
install(FILES third_party/gbarecomp/src/runtime/bios_hle.cpp third_party/gbarecomp/src/runtime/bios_hle.h DESTINATION "${MAC_APP}/Resources/license-source/bios_hle")
include(CTest)
if(BUILD_TESTING)
  foreach(test zip online connection chat motion world_sync wager camp battle_presence release campaign encounter_retry world_store)
    add_executable(fr_${test}_tests tests/${test}_tests.cpp)
    target_link_libraries(fr_${test}_tests PRIVATE fr_online)
    add_test(NAME ${test} COMMAND fr_${test}_tests)
    set_tests_properties(${test} PROPERTIES TIMEOUT 90)
  endforeach()
  foreach(test labels follower)
    add_executable(fr_${test}_tests tests/${test}_tests.cpp)
    target_link_libraries(fr_${test}_tests PRIVATE fr_labels)
    add_test(NAME ${test} COMMAND fr_${test}_tests)
  endforeach()
  foreach(test bios_service serial_device composition hook_registry)
    add_executable(fr_${test}_tests tests/${test}_tests.cpp)
    target_link_libraries(fr_${test}_tests PRIVATE fr_core gbarecomp_runtime)
    add_test(NAME ${test} COMMAND fr_${test}_tests)
  endforeach()
endif()
